$ErrorActionPreference='Stop'
$projects=@('A70.AMITWP','A72.TOUTWP','test-proyecto','_template')
$base='c:\Users\mpugnaghi\Documents\Work_In_Process\_Web\AI test\SW.PC.API.Backend_\Projects'

# Unicode chars (distinct lowercase var names — PowerShell is case-insensitive)
$eacu  = [char]0x00E9   # é
$agra  = [char]0x00E0   # à
$iacu  = [char]0x00ED   # í
$oacu  = [char]0x00F3   # ó
$aacu  = [char]0x00E1   # á
$acir  = [char]0x00E2   # â
$ecap  = [char]0x00C9   # É
$midd  = [char]0x00B7   # ·
$mdas  = [char]0x2014   # —

$keys = [ordered]@{
  'statistics.order.ui.channel.wizard.label' = @{
    SPA = 'Gestor de Exportaciones'
    ENG = 'Export Manager'
    FRA = "Gestionnaire d'exportations"
    ITA = 'Gestore esportazioni'
  }
  'statistics.order.ui.channel.wizard.sub' = @{
    SPA = 'Tareas persistentes'
    ENG = 'Persistent tasks'
    FRA = "T${acir}ches persistantes"
    ITA = "Attivit${agra} persistenti"
  }
  'statistics.order.printable.title' = @{
    SPA = 'Pedido de consumibles'
    ENG = 'Consumables order'
    FRA = 'Commande de consommables'
    ITA = 'Ordine consumabili'
  }
  'statistics.order.printable.sub' = @{
    SPA = "Aquafrisch Supervisor ${midd} SMM"
    ENG = "Aquafrisch Supervisor ${midd} SMM"
    FRA = "Aquafrisch Supervisor ${midd} SMM"
    ITA = "Aquafrisch Supervisor ${midd} SMM"
  }
  'statistics.order.printable.ref'     = @{ SPA='Referencia';   ENG='Reference';    FRA="R${eacu}f${eacu}rence";      ITA='Riferimento' }
  'statistics.order.printable.date'    = @{ SPA='Fecha';        ENG='Date';         FRA='Date';                       ITA='Data' }
  'statistics.order.printable.project' = @{ SPA='Proyecto';     ENG='Project';      FRA='Projet';                     ITA='Progetto' }
  'statistics.order.printable.element' = @{ SPA='Elemento';     ENG='Element';      FRA="${ecap}l${eacu}ment";        ITA='Elemento' }
  'statistics.order.printable.by'      = @{ SPA='Generado por'; ENG='Generated by'; FRA="G${eacu}n${eacu}r${eacu} par"; ITA='Generato da' }
  'statistics.order.printable.lines'   = @{ SPA="L${iacu}neas"; ENG='Lines';        FRA='Lignes';                     ITA='Righe' }
  'statistics.order.printable.notes'   = @{ SPA='Notas';        ENG='Notes';        FRA='Notes';                      ITA='Note' }
  'statistics.order.printable.footer'  = @{
    SPA = "Documento generado autom${aacu}ticamente por Aquafrisch Supervisor ${mdas} SMM Module."
    ENG = "Document automatically generated by Aquafrisch Supervisor ${mdas} SMM Module."
    FRA = "Document g${eacu}n${eacu}r${eacu} automatiquement par Aquafrisch Supervisor ${mdas} SMM Module."
    ITA = "Documento generato automaticamente da Aquafrisch Supervisor ${mdas} SMM Module."
  }
  'statistics.order.printable.col.sku'         = @{ SPA='SKU';                  ENG='SKU';         FRA='SKU';                  ITA='SKU' }
  'statistics.order.printable.col.description' = @{ SPA="Descripci${oacu}n";    ENG='Description'; FRA='Description';          ITA='Descrizione' }
  'statistics.order.printable.col.quantity'    = @{ SPA='Cantidad';             ENG='Quantity';    FRA="Quantit${eacu}";       ITA="Quantit${agra}" }
  'statistics.order.printable.col.unit'        = @{ SPA='Unidad';               ENG='Unit';        FRA="Unit${eacu}";          ITA="Unit${agra}" }
  'statistics.order.printable.col.element'     = @{ SPA='Elemento';             ENG='Element';     FRA="${ecap}l${eacu}ment";  ITA='Elemento' }
}

foreach($p in $projects){
  $f = Join-Path $base "$p\translations\translations.json"
  if(-not(Test-Path $f)){ Write-Host "SKIP $p"; continue }
  $raw = [System.IO.File]::ReadAllText($f, [System.Text.Encoding]::UTF8)
  $j = $raw | ConvertFrom-Json
  if(-not $j.translations){ Write-Host "NO translations in $p"; continue }
  foreach($k in $keys.Keys){
    $j.translations | Add-Member -NotePropertyName $k -NotePropertyValue ([pscustomobject]$keys[$k]) -Force
  }
  $out = $j | ConvertTo-Json -Depth 100
  [System.IO.File]::WriteAllText($f, $out, (New-Object System.Text.UTF8Encoding($false)))
  Write-Host "OK $p"
}
try {
  Invoke-RestMethod -Uri http://localhost:5000/api/translations/clear-cache -Method Post -TimeoutSec 5 | Out-Null
  Write-Host 'Cache cleared'
} catch { Write-Host "Cache clear FAIL: $($_.Exception.Message)" }
